[build]
  publish = "public"
  command = "echo 'Build complete'"

[[redirects]]
  from = "/rentals/*"
  to = "/rentals/index.html"
  status = 200

[[redirects]]
  from = "/food/*"
  to = "/food/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "echo 'Production build'"
  publish = "public"
